spring:
  datasource:
    url: jdbc:h2:mem:api;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  flyway:
    enabled: false
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

file:
  show:
    upload:
      location: /test
