spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  servlet:
    context-path: /api

management:
  server:
    port: 9000
  endpoints:
    web:
      exposure:
        include: prometheus, health
